export const movies = [
  {
    id: 1,
    title: "La La Land",
    year: 2016,
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    genres: ["Romance", "Drama", "Musical"],
    subGenres: ["Rom-Com", "Original Score"],
    moods: ["Emotional", "Nostalgic", "Romantic", "Hopeful"],
    vibes: ["Feel-Good", "Deep & Meaningful", "Visually Stunning"],
    language: "English",
    release: "Modern Classic (2000–2019)",
    platforms: ["Netflix", "Hulu"],
    overview:
      "A pianist and an actress fall in love while pursuing their dreams in Los Angeles.",
  },
  {
    id: 2,
    title: "Whiplash",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    genres: ["Drama"],
    subGenres: ["Artist Story"],
    moods: ["Intense", "Empowering"],
    vibes: ["Fast-Paced", "Deep & Meaningful", "Edge-of-Seat"],
    language: "English",
    release: "Modern Classic (2000–2019)",
    platforms: ["Netflix", "Prime Video"],
    overview:
      "A young drummer pushes himself to the limit under a ruthless music instructor.",
  },
  {
    id: 3,
    title: "Coco",
    year: 2017,
    poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    genres: ["Animation", "Fantasy", "Adventure"],
    subGenres: ["Family Animation", "Mythological"],
    moods: ["Heartwarming", "Emotional", "Hopeful"],
    vibes: ["Feel-Good", "Cozy & Warm", "Visually Stunning"],
    language: "English",
    release: "Modern Classic (2000–2019)",
    platforms: ["Disney+"],
    overview:
      "A young musician enters the Land of the Dead to uncover his family history.",
  },
  {
    id: 4,
    title: "Inception",
    year: 2010,
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    genres: ["Sci-Fi", "Thriller", "Action"],
    subGenres: ["Mind-Bending", "Time Travel", "Heist"],
    moods: ["Intense", "Mysterious", "Thrilling"],
    vibes: ["Mind-Bending", "Fast-Paced", "Thought-Provoking"],
    language: "English",
    release: "Modern Classic (2000–2019)",
    platforms: ["Prime Video"],
    overview:
      "A thief enters dreams to steal secrets and is offered a chance at redemption.",
  },
  {
    id: 5,
    title: "Parasite",
    year: 2019,
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    genres: ["Thriller", "Drama", "Crime"],
    subGenres: ["Dark Comedy", "Plot Twist Heavy"],
    moods: ["Dark", "Suspenseful", "Mysterious"],
    vibes: ["Thought-Provoking", "Dark & Gritty", "Edge-of-Seat"],
    language: "Korean",
    release: "Modern Classic (2000–2019)",
    platforms: ["Hulu"],
    overview:
      "A poor family schemes their way into the lives of a wealthy household.",
  },
  {
    id: 6,
    title: "Interstellar",
    year: 2014,
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    subGenres: ["Space", "Dystopian"],
    moods: ["Emotional", "Inspirational", "Reflective"],
    vibes: ["Epic & Grand", "Thought-Provoking", "Visually Stunning"],
    language: "English",
    release: "Modern Classic (2000–2019)",
    platforms: ["Prime Video"],
    overview:
      "A team travels through a wormhole to find humanity a new home.",
  },
];